### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by cr1bug** [SiJiDo/IEyes#1]
win10
cmd、powershell、bash都报此错误

❯ .\IEyes.exe -n 京东
[+]开始准备获取当前公司名称
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.GetFirstCompany(0xc0000c6000, 0xb6, 0xc0000103e0, 0x1e, 0xc000006048, 0x0, 0x0, 0xb391c3, 0x16, 0xc00006ede0)
        /Users/mi0/tool/srctool/git/IEyes/main/basefunc.go:95 +0x705
main.main()
        /Users/mi0/tool/srctool/git/IEyes/main/main.go:92 +0x1a85

**Comment by SiJiDo** [comment]
有时候会报错，可能是爬取的数据处理有问题，这种情况加上-child就不报错了.....

**Comment by SiJiDo** [comment]
我试了还是报错，确实有bug，我有空研究下..
